### ISSUE TITLE
Loading MF Remote as ESM

### ISSUE THREAD

**Issue by manfredsteyer** [picardjs/picard#3]
It seems like MF is currently always loaded as a script file. Is there a way to load it as an ESM to prevent this issue:

![image](https://github.com/picardjs/picard/assets/1573728/1cf25145-bcc9-45fb-9092-715ff08d0ed7)

Angular is just using ESM, meanwhile.

**Comment by FlorianRappl** [comment]
How can we know if it should be ESM or not from the outside?

Webpack itself is just loading these as scripts. I think you might use another remote target (the default is `var`, but there are others which may indicate an ESM - but `var` is historically the default and therefore right now supported out of the box). Other targets may require the JSON (manifest) instead of the plain JS (or we introduce another specifier / attribute when using it single handed).

**Comment by manfredsteyer** [comment]
We could add a parameter to specify its `esm`. In our Angular API we also had such an option (type: 'module' | 'script').

**Comment by FlorianRappl** [comment]
This should be solved in the 0.0.6 that is already available on npm.

- `container` (in attributes) is now called `remote-name`
- the remote type (in attributes) is called `remote-type`

Specifying the remote type is optional. The two available types are `var` (default) and `esm` (equivalent to library type being set to `module`).

Let me know if this works for you (works in my testing - see [example 10; dependency sharing](https://github.com/picardjs/picard/tree/main/examples/10-dependencies-sharing)).
